# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kulti < Formula
  desc "CLI tool for creating and managing k3s clusters on local hypervisors"
  homepage "https://zpallin.com/kulti"
  version "0.2.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://gitlab.com/zpallin/kulti/-/releases/v0.2.11/downloads/kulti_0.2.11_darwin_amd64.tar.gz"
      sha256 "f21ae93eb65d2536b9fbaef1fe8d196e85b67ecff01fc178a8ec496361a765c1"

      define_method(:install) do
        bin.install "kulti"
      end
    end
    if Hardware::CPU.arm?
      url "https://gitlab.com/zpallin/kulti/-/releases/v0.2.11/downloads/kulti_0.2.11_darwin_arm64.tar.gz"
      sha256 "5963bae6712599a43caf438a2c71101eebf4cb63c6d5796d2993976a4ae7eb4e"

      define_method(:install) do
        bin.install "kulti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://gitlab.com/zpallin/kulti/-/releases/v0.2.11/downloads/kulti_0.2.11_linux_amd64.tar.gz"
      sha256 "23d7e2765ed7675e2794e3705e6f67740f0b29dd1f0ec39fba0969eab2fcecfe"
      define_method(:install) do
        bin.install "kulti"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gitlab.com/zpallin/kulti/-/releases/v0.2.11/downloads/kulti_0.2.11_linux_arm64.tar.gz"
      sha256 "457d80fa74f9b4ae0e35e8d0de6fa68831504ea9da823b470dd6ca4361b6f64a"
      define_method(:install) do
        bin.install "kulti"
      end
    end
  end

  test do
    system "#{bin}/kulti", "version"
  end
end
