# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kulti < Formula
  desc "CLI tool for creating and managing k3s clusters on local hypervisors"
  homepage "https://zpallin.com/kulti"
  version "0.2.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://gitlab.com/zpallin/kulti/-/releases/v0.2.12/downloads/kulti_0.2.12_darwin_amd64.tar.gz"
      sha256 "798b2668a1dafd80b701f41833b32a811b75a5540be81470812072510a4c2a1e"

      define_method(:install) do
        bin.install "kulti"
      end
    end
    if Hardware::CPU.arm?
      url "https://gitlab.com/zpallin/kulti/-/releases/v0.2.12/downloads/kulti_0.2.12_darwin_arm64.tar.gz"
      sha256 "73deb36a056d2642d4c7c022ae790c2e49e72c43a60e52dc4dfae3fc30be741f"

      define_method(:install) do
        bin.install "kulti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://gitlab.com/zpallin/kulti/-/releases/v0.2.12/downloads/kulti_0.2.12_linux_amd64.tar.gz"
      sha256 "be6be7c4ff42d96680f45c25ad0e062b96bce210ed6c9e4202fc00c98ca621e0"
      define_method(:install) do
        bin.install "kulti"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gitlab.com/zpallin/kulti/-/releases/v0.2.12/downloads/kulti_0.2.12_linux_arm64.tar.gz"
      sha256 "409b283bbfbc0d09a8dd036026793b1e88fd1dcc931ce51e48ce2402edc5dc69"
      define_method(:install) do
        bin.install "kulti"
      end
    end
  end

  test do
    system "#{bin}/kulti", "version"
  end
end
