# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kulti < Formula
  desc "CLI tool for creating and managing k3s clusters on local hypervisors"
  homepage "https://zpallin.com/kulti"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://gitlab.com/zpallin/kulti/-/releases/v0.3.2/downloads/kulti_0.3.2_darwin_amd64.tar.gz"
      sha256 "b41ef1c323f96e82fda1a731048d560e834f32190fbfde3d178e71e891f5af41"

      define_method(:install) do
        bin.install "kulti"
      end
    end
    if Hardware::CPU.arm?
      url "https://gitlab.com/zpallin/kulti/-/releases/v0.3.2/downloads/kulti_0.3.2_darwin_arm64.tar.gz"
      sha256 "8cfb330f251cc2c181218ca9fb02065eaca6cb2985cb8346d9a7811f730f8d2c"

      define_method(:install) do
        bin.install "kulti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://gitlab.com/zpallin/kulti/-/releases/v0.3.2/downloads/kulti_0.3.2_linux_amd64.tar.gz"
      sha256 "db0248ba512833b1cd3d16ed90fa34077ddf8f2cd4c3a44e11e9001a207dab89"
      define_method(:install) do
        bin.install "kulti"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gitlab.com/zpallin/kulti/-/releases/v0.3.2/downloads/kulti_0.3.2_linux_arm64.tar.gz"
      sha256 "1912c8c13724a1fe734c2012438633401406a81c8ce3ac80f759e6495dfaca3a"
      define_method(:install) do
        bin.install "kulti"
      end
    end
  end

  test do
    system "#{bin}/kulti", "version"
  end
end
