# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kulti < Formula
  desc "CLI tool for creating and managing k3s clusters on local hypervisors"
  homepage "https://zpallin.com/kulti"
  version "0.1.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://gitlab.com/zpallin/kulti/-/releases/v0.1.11/downloads/kulti_0.1.11_darwin_amd64.tar.gz"
      sha256 "48b9c560fbaf619e6ca4caef50d85deada0400193fc974d889419904c8bef222"

      define_method(:install) do
        bin.install "kulti"
      end
    end
    if Hardware::CPU.arm?
      url "https://gitlab.com/zpallin/kulti/-/releases/v0.1.11/downloads/kulti_0.1.11_darwin_arm64.tar.gz"
      sha256 "ac0ed3a1f24fad7d28f516bda09d5533ab8ff92982d10d1e9f68b769695cc20f"

      define_method(:install) do
        bin.install "kulti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://gitlab.com/zpallin/kulti/-/releases/v0.1.11/downloads/kulti_0.1.11_linux_amd64.tar.gz"
      sha256 "583b1302551dc596a9a8259cd1723d8c5f8877c26fbe84e5b0f299b1dbc75d9f"
      define_method(:install) do
        bin.install "kulti"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gitlab.com/zpallin/kulti/-/releases/v0.1.11/downloads/kulti_0.1.11_linux_arm64.tar.gz"
      sha256 "8e6f516d7021cad05a40345433322b558d8964aa1d0a9942f58c4e1ede1d3b1f"
      define_method(:install) do
        bin.install "kulti"
      end
    end
  end

  test do
    system "#{bin}/kulti", "version"
  end
end
